services:
  markdown_api:
    build: .
    container_name: markdown_api
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9010:9000"  # S3-compatible API
      - "9001:9001"  # MinIO Web Console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    restart: unless-stopped

volumes:
  minio_data:
